const params=new URLSearchParams(location.search);const jobName=params.get('job');document.getElementById('jobTitle').textContent=jobName?`Job Entry — ${jobName}`:'Job Entry';
async function refreshStatus(){const j=await get('jobs',jobName);document.getElementById('jobStatus').textContent=j?.status||'in-progress';const locked=j?.status==='complete';for(const id of ['timeDate','regHours','otHours','miles','milesNotes','hotelNights','hotelCost','partItem','partCost','receiptFile']){const el=document.getElementById(id);if(el)el.disabled=locked;}document.getElementById('addTimeBtn').disabled=locked;document.getElementById('addMileageBtn').disabled=locked;document.getElementById('addHotelBtn').disabled=locked;document.getElementById('addPartBtn').disabled=locked;document.getElementById('addReceiptBtn').disabled=locked;document.getElementById('markCompleteBtn').disabled=locked;}
refreshStatus();
function uid(){return jobName+':'+crypto.randomUUID();}
document.getElementById('addTimeBtn').addEventListener('click',async()=>{const r={id:uid(),job:jobName,date:document.getElementById('timeDate').value,reg:+(document.getElementById('regHours').value||0),ot:+(document.getElementById('otHours').value||0)};await put('time',r);alert('Time saved');});
document.getElementById('addMileageBtn').addEventListener('click',async()=>{const r={id:uid(),job:jobName,miles:+(document.getElementById('miles').value||0),notes:document.getElementById('milesNotes').value};await put('mileage',r);alert('Mileage saved');});
document.getElementById('addHotelBtn').addEventListener('click',async()=>{const r={id:uid(),job:jobName,nights:+(document.getElementById('hotelNights').value||0),cost:+(document.getElementById('hotelCost').value||0)};await put('hotels',r);alert('Hotel saved');});
document.getElementById('addPartBtn').addEventListener('click',async()=>{const r={id:uid(),job:jobName,item:document.getElementById('partItem').value,cost:+(document.getElementById('partCost').value||0)};await put('parts',r);alert('Part saved');});
document.getElementById('addReceiptBtn').addEventListener('click',async()=>{const f=document.getElementById('receiptFile').files[0];if(!f){alert('Choose a file');return;}const buf=await f.arrayBuffer();const r={id:uid(),job:jobName,name:f.name,type:f.type,data:new Blob([buf],{type:f.type})};await put('receipts',r);alert('Receipt saved');});
document.getElementById('markCompleteBtn').addEventListener('click',async()=>{const j=await get('jobs',jobName);if(!j)return;j.status='complete';await put('jobs',j);await refreshStatus();alert('Job marked complete. Entries locked.');});
document.getElementById('backBtn').addEventListener('click',()=>window.location.href='jobView.html');